### PR TITLE
Keyboard fixes

### LINKED ISSUE #40: KevEdit captures wm-specific key combinations
When I switch to KevEdit on Linux by using Alt+Tab, the key combination sometimes triggers drawing mode in KevEdit as if I had manually pressed Tab. This doesn't happen all the time, but it's annoying when it does happen.

I'm using xfce. This doesn't happen with any of the other applications I'm using, so I don't think it's window manager problem unless there's some odd interaction effect with SDL.

### PR DESCRIPTION
**Pull request by kristomu**
This should fix #40 and also allows the use of international characters in things like board names, by creating CP437-specific variants of toupper() and tolower().

Things to note: the new files for upper/lowercase may not be in the right spot (src/display?), and hotkeys that aren't bound still removes literals (see the commit for more info).

### CODE REVIEW

**Comment by kristomu** [comment]
(We might still need the special-casing for ALT+TAB as TAB is not a literal, but it should handle all ALT+literal combinations.)

**Comment by kristomu** [comment]
#40 wasn't fully fixed, added a commit that does fix alt+tab on my system.

File: src/display/display_sdl.c [hunk 1]
```diff
@@ -600,6 +600,29 @@ static int has_unicode_event_queued()
...
+		MAX_EVENTS, SDL_PEEKEVENT, event_type,
+		event_type);
+
+	if (pending_events == 0)
+		return;
+
+	SDL_PeepEvents(outevent, 1, SDL_GETEVENT,
+		event_type, event_type);
+
+	return;
```
Comment (cknave) [inline src/display/display_sdl.c]: Since we're only looking for one type of event (minType == maxType == event_type) and then immediately getting it (and discarding it), we can just use `SDL_GETEVENT` and ignore the return value:

```suggestion
	SDL_Event outevent;
	SDL_PeepEvents(&outevent, 1, SDL_GETEVENT,
		event_type, event_type);
```

**Comment by cknave** [comment]
Thanks! I couldn't reproduce the original issue with `kwin_x11` but this looks good to me

**Comment by kristomu** [comment]
It might be an XFCE thing for all I know :-)
By the way, while debugging, I saw some SDL_TEXTEDITING events, which apparently have to do with IME (even though I'm not using IME). If someone reports a bug with IME or other text editing tools, that may be relevant.
